FROM python:3.9-slim
ENV PATH="/usr/local/cuda/bin:${PATH}"
ENV LD_LIBRARY_PATH="/usr/local/cuda/lib64:${LD_LIBRARY_PATH}"
# RUN apt-get update && apt-get install ffmpeg libsm6 libxext6 libmagic-dev libgl1-mesa-glx git git-lfs git-man less libcbor0.8 libcurl3-gnutls liberror-perl libfido2-1 libgdbm-compat4 libldap-2.5-0 libldap-common libnghttp2-14 libperl5.36  libpsl5 librtmp1 libsasl2-2 libsasl2-modules libsasl2-modules-db libssh2-1 libxmuu1 openssh-client patch perl perl-modules-5.36 publicsuffix xauth -y
# Set the working directory to /app
WORKDIR /app
# Copy only the project to the container
COPY . /app
# RUN git lfs pull
# Install the required packages
RUN pip install -r requirements.txt
# Expose port 7000 for the API
EXPOSE 8000
# Start the API with Uvicorn
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "test_website.wsgi:application"]
