# Generated by Django 4.2.4 on 2024-01-20 07:26

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interface_type', models.CharField(choices=[('tab_details', 'Tab Details'), ('pre_assessment', 'Pre Assessment'), ('borrower_ui_common', 'borrower_ui_common'), ('borrower_ui', 'Borrower UI'), ('backoffice_ui', 'Backoffice UI'), ('backoffice_config', 'Backoffice Config'), ('kyc', 'KYC'), ('documentation_system', 'WKFS'), ('start_tabs', 'Initial Tabs on UI'), ('end_tabs', 'Final Tabs on UI'), ('organization_config', 'Organization Configuration'), ('product_config', 'Product Configuration'), ('preliminary_document', 'Preliminary Document'), ('borrower_notifications', 'Borrower Notification Configuration'), ('lender_notifications', 'Lender Notification Configuration'), ('security', 'Security Configuration'), ('esign_config', 'Esign Configuration'), ('product_validation', 'Product Validation'), ('boarding_document_extract', 'Boarding Document Extract'), ('risk_review_config', 'Risk Review Configuration'), ('conditional_risk_review', 'Conditional Risk Review'), ('cbr_aggregation', 'CBR Aggregation Configuration'), ('fico', 'FICO'), ('experian', 'EXPERIAN'), ('service_requests', 'Service Requests'), ('tax', 'Tax Transcript Configuration'), ('annual_review', 'Annual Review Configuration'), ('questionaire', 'Questionaire'), ('fico-aggregator', 'Fico Aggregation Specifications'), ('fico-aggregator-config', 'Input for Fico Aggregation'), ('fico-aggregator-func', 'Functions utilized in Fico Aggregator JQ'), ('experian-aggregator', 'Experian Aggregation Specifications'), ('experian-aggregator-config', 'Input for Experian Aggregation'), ('experian-aggregator-func', 'Functions utilized in Experian Aggregator JQ'), ('experian-mapper', 'Experian Codes Mapper Specification'), ('fico-mapper', 'Fico Codes Mapper Specification'), ('cbr-mapper-config', 'Input for CBR Codes Mapper'), ('cbr-mapper-func', 'Functions Utilized in CBR Mapper JQ'), ('it_notifications', 'IT Service Request Notification Configuration'), ('sso', 'SSO Configurations'), ('loan_exceptions_config', 'Loan Exceptions Configuration'), ('rerun_config', 'Rerun Configuration'), ('property-report-spec', 'Property Report Spec configuration'), ('business_spread_template', 'Spreading Template - Business'), ('global_spread_template', 'Spreading Template - Global'), ('individual_spread_template', 'Spreading Template - Individual'), ('cre_office_spread_template', 'Spreading Template - CRE Office'), ('cre_global_spread_template', 'Spreading Template - CRE Global'), ('cre_multifamily_spread_template', 'Spreading Template - CRE Multifamily'), ('cre_office_annual_spread_template', 'Spreading Template - CRE Office - Annual'), ('cre_multifamily_annual_spread_template', 'Spreading Template - CRE Multifamily - Annual'), ('it_config', 'IT Service Request configuration'), ('etran_transformer', 'Etran Transformer Specifications'), ('etran_transformer_config', 'Input for Etran Transformer'), ('collateral_desc_config', 'Description text for all collateral types'), ('sso', 'SSO Configurations'), ('reevaluation', 'Re-evaluation'), ('ebilling_payments', 'E-billing Payments'), ('etran', 'E-tran configuration'), ('wkfs_transformer_config', 'WKFS Transformer Config'), ('wkfs_admin_config_LA', 'WKFS Admin Config LA'), ('reason_test_mapping', 'Reason Test Mapping'), ('corelogic_transformer_spec', 'Corelogic Transformer Spec'), ('financial_data_aggregator', 'financial_data_aggregator'), ('form5c_spec', 'Form 5C Spec'), ('form5_spec', 'FORM 5 Spec'), ('plesionyms_config', 'Plesionyms Config'), ('credit_bureau_tests', 'Credit Bureau Exception Tests'), ('debt_account_types', 'Debt Account Types'), ('reconsideration_config', 'Reconsideration Config'), ('taxguard_normalizer_spec', 'Taxguard Normalizer Spec'), ('ci-etran-create_loan_dph', 'ci-etran-create_loan_dph'), ('ci-etran-create_loan_dpb', 'ci-etran-create_loan_dpb'), ('ci-etran-create_loan', 'ci-etran-create_loan'), ('rate_config', 'Rate Config'), ('ci-tenant-map', 'ci-tenant-map'), ('ci-etran-loan-type', 'ci-etran-loan-type'), ('fema', 'FEMA'), ('ci-etran-common', 'ci-etran-common'), ('ci-etran-create_disb', 'ci-etran-create_disb'), ('integration_config', 'Integration Configuration'), ('ci-etran-servicing_deferment', 'ci-etran-servicing_deferment'), ('ci-etran-loanstatuscode', 'ci-etran-loanstatuscode'), ('ci-etran-create_disb_mobilehome', 'ci-etran-create_disb_mobilehome'), ('ci-etran-update_loanamt_dpb', 'ci-etran-update_loanamt_dpb'), ('ci-etran-update_loanamt_dph', 'ci-etran-update_loanamt_dph'), ('ci-etran-cancel_loan', 'ci-etran-cancel_loan'), ('ci-etran-diff_original_payload_dpb', 'ci-etran-diff_original_payload_dpb'), ('ci-etran-diff_original_payload_dph', 'ci-etran-diff_original_payload_dph'), ('ci-etran-diff_updated_payload_dph', 'ci-etran-diff_updated_payload_dph'), ('ci-etran-diff_updated_payload_dpb', 'ci-etran-diff_updated_payload_dpb'), ('ci-etran-disb-uop-threshold', 'ci-etran-disb-uop-threshold'), ('conversion', 'DCMS conversion'), ('ci-etran-reinstate_loan', 'ci-etran-reinstate_loan'), ('mitigation', 'Mitigation Suggestions'), ('lender_match', 'Lender Match Settings')], max_length=255, verbose_name='Interface Type')),
                ('name', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
