# Generated by Django 4.2.9 on 2024-01-20 13:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterDeclaration',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('db_disaster_number', models.PositiveIntegerField(blank=True, null=True)),
                ('disaster_number', models.CharField(blank=True, default='', max_length=255, verbose_name='Disaster Number')),
                ('db_physical_damage_number', models.PositiveIntegerField(blank=True, null=True)),
                ('db_eidl_damage_number', models.PositiveIntegerField(blank=True, null=True)),
                ('disaster_description', models.CharField(blank=True, default='', max_length=255, verbose_name='Disaster Description')),
                ('disaster_initiator', models.CharField(blank=True, default='', max_length=128, verbose_name='Disaster Initiator')),
                ('primary_disaster_state', models.CharField(blank=True, max_length=100, null=True, verbose_name='Primary State')),
                ('primary_counties', models.JSONField(blank=True, default=list, verbose_name='Primary Locales')),
                ('contiguous_counties', models.JSONField(blank=True, default=list, verbose_name='Contiguous Locales')),
                ('tribal_regions', models.JSONField(blank=True, default=list, verbose_name='Tribal Regions')),
                ('damage_type_code', models.CharField(blank=True, choices=[('0', '0 - EIDL'), ('1', '1 - DEPT OF AG(FSA) EIDL'), ('2', '2 - EARTHQUAKES'), ('4', '4 - EXPLOSIONS'), ('5', '5 - FIRES'), ('6', '6 - FLOODS'), ('7', '7 - FREEZES'), ('8', '8 - HURRICANES'), ('9', '9 - LANDSLIDES/MUDSLIDES'), ('B', 'B - STORMS'), ('C', 'C - TORNADOES'), ('D', 'D - VOLCANIC ERUPTIONS'), ('E', 'E - OTHER: NATURAL'), ('F', 'F - OTHER: MANMADE'), ('U', 'U - UNKNOWN')], default='', max_length=2, verbose_name='Disaster Damage Type')),
                ('contact_person', models.CharField(blank=True, default='', max_length=255, verbose_name='Contact Person')),
                ('form_605_remarks', models.TextField(blank=True, default='', verbose_name='Form 605 Remarks')),
                ('disaster_status', models.IntegerField(blank=True, choices=[(0, 'Disaster New'), (1, 'Preparing Survey'), (2, 'Survey In Progress'), (3, 'Pending Survey Validation'), (4, 'Survey Validated'), (5, 'FEMA Declined'), (6, 'Survey Review'), (7, 'Resurvey Requested'), (8, 'Declaration Review'), (9, 'Declaration Approved'), (10, 'Pending Admin Approval'), (11, 'Disaster Declared'), (12, 'Amend Requested'), (13, 'Disaster Canceled')], default=0, null=True, verbose_name='Disaster Status')),
                ('fema_number', models.CharField(blank=True, default='', max_length=255, verbose_name='FEMA Number')),
                ('usda_agency_number', models.CharField(blank=True, default='', max_length=255, verbose_name='USDA Agency Number')),
                ('incident_start_date', models.DateField(blank=True, null=True, verbose_name='Incident Start Date')),
                ('incident_end_date', models.DateField(blank=True, null=True, verbose_name='Incident End Date')),
                ('request_date', models.DateField(blank=True, null=True, verbose_name='Request Date')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='Received Date')),
                ('geographic_multiplier', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Geographic Multiplier')),
                ('physical_declaration_number', models.CharField(blank=True, default='', max_length=255, verbose_name='Physical Declaration Number')),
                ('physical_deadline_date', models.DateField(blank=True, null=True, verbose_name='Physical Deadline Date')),
                ('physical_unsecured_limit', models.DecimalField(blank=True, decimal_places=2, default=25000, max_digits=16, null=True, verbose_name='Physical Unsecured Limit')),
                ('eidl_declaration_number', models.CharField(blank=True, default='', max_length=255, verbose_name='EIDL Declaration Number')),
                ('eidl_deadline_date', models.DateField(blank=True, null=True, verbose_name='EIDL Deadline Date')),
                ('eidl_unsecured_limit', models.DecimalField(blank=True, decimal_places=2, default=25000, max_digits=16, null=True, verbose_name='EIDL Unsecured Limit')),
                ('declaration_date', models.DateField(blank=True, null=True, verbose_name='Declaration Date')),
                ('disbursement_period_months', models.IntegerField(default=6, verbose_name='Disbursement Period (Months)')),
                ('grace_period_days', models.IntegerField(default=15, verbose_name='Grace Period (Days)')),
                ('payment_deferment_period_months', models.IntegerField(default=11, verbose_name='Payment Deferment Period')),
                ('first_payment_due_months', models.IntegerField(default=12, verbose_name='First Payment Due')),
                ('initial_disbursement_limit', models.IntegerField(default=50000, verbose_name='Amount that can be initially disbursed for a loan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('naics_code_set', models.IntegerField(blank=True, null=True, verbose_name='NAICS Data Set Year')),
                ('interest_rate', models.JSONField(blank=True, default=dict, verbose_name='Interest Rate')),
                ('is_survey_required', models.BooleanField(default=True, verbose_name='Is Survey Required')),
                ('is_ulp_serviced', models.BooleanField(default=False, verbose_name='Is ULP Serviced')),
                ('cancel_notes', models.TextField(blank=True, null=True)),
                ('cancel_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, choices=[('state_withdraw', 'State Withdraw'), ('sba_decline', 'SBA Decline'), ('void', 'Void')], max_length=20, null=True)),
                ('document_data', models.JSONField(blank=True, default=dict, verbose_name='Document Data')),
                ('source_external_files', models.JSONField(blank=True, default=list, verbose_name='External Files from Legacy system')),
                ('survey_request_date', models.DateField(blank=True, null=True, verbose_name='Survey Request Date')),
                ('survey_received_date', models.DateField(blank=True, null=True, verbose_name='Survey Received Date')),
                ('reinstatement_period', models.IntegerField(default=60, verbose_name='Reinstatement Period (Days)')),
                ('signer_details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Product Type Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Product Type Description')),
                ('product_type_code', models.CharField(choices=[('LOC', 'Line of Credit'), ('TL', 'Term Loan'), ('SR', 'Service Request'), ('EL', 'SBA Express Loan'), ('DL', 'Disaster Business Loan')], max_length=15, unique=True, verbose_name='Product Type Code')),
                ('is_removed', models.BooleanField(default=False)),
            ],
            options={
                'permissions': [('can_view_product_types', 'Can View Product Types')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Product Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Product Description')),
                ('product_code', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Product Code')),
                ('fi_product_code', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='FI Product Code')),
                ('min_term_in_months', models.PositiveSmallIntegerField(default=1, verbose_name='Min Term in Months')),
                ('max_term_in_months', models.PositiveSmallIntegerField(default=180, verbose_name='Max Term in Months')),
                ('min_rate', models.FloatField(default=0.0, verbose_name='Minimum Interest Rate')),
                ('max_rate', models.FloatField(default=36.0, verbose_name='Maximum Interest Rate')),
                ('is_express_loan', models.BooleanField(default=False)),
                ('is_demand_feature_loan', models.BooleanField(default=False)),
                ('is_multiterm', models.BooleanField(default=False)),
                ('file_due_in_days', models.PositiveSmallIntegerField(default=14)),
                ('is_removed', models.BooleanField(default=False)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configurations.producttype')),
            ],
            options={
                'permissions': [('can_view_products', 'Can View Products')],
            },
        ),
    ]
